declare const styles: {
  readonly 'container-base': string;
  readonly 'punctuation-base': string;
  readonly 'expander-base': string;
  readonly 'pointer': string;
  readonly 'container-light': string;
  readonly 'expander-light': string;
  readonly 'basic-element-style': string;
  readonly 'label-light': string;
  readonly 'punctuation-light': string;
  readonly 'value-null-light': string;
  readonly 'value-undefined-light': string;
  readonly 'value-string-light': string;
  readonly 'value-number-light': string;
  readonly 'value-boolean-light': string;
  readonly 'value-other-light': string;
  readonly 'container-dark': string;
  readonly 'expander-dark': string;
  readonly 'label-dark': string;
  readonly 'punctuation-dark': string;
  readonly 'value-null-dark': string;
  readonly 'value-undefined-dark': string;
  readonly 'value-string-dark': string;
  readonly 'value-number-dark': string;
  readonly 'value-boolean-dark': string;
  readonly 'value-other-dark': string;
};
export = styles;