import * as PropTypes from 'prop-types';
import * as React from 'react';
import { IArchbaseSpaceCommonProps, IResizeHandleProps } from '../core-react';
import { ResizeHandlePlacement, SizeUnit } from '../core-types';
export interface IArchbaseResizableProps extends IArchbaseSpaceCommonProps {
    size: SizeUnit;
    order?: number;
    handleSize?: number;
    touchHandleSize?: number;
    handlePlacement?: ResizeHandlePlacement;
    handleRender?: (handleProps: IResizeHandleProps) => React.ReactNode;
    minimumSize?: number;
    maximumSize?: number;
    onResizeStart?: () => void | boolean;
    onResizeEnd?: (newSize: SizeUnit) => void;
}
export declare const resizableProps: {
    size: PropTypes.Validator<NonNullable<NonNullable<string | number>>>;
    order: PropTypes.Requireable<number>;
    handleSize: PropTypes.Requireable<number>;
    touchHandleSize: PropTypes.Requireable<number>;
    handlePlacement: PropTypes.Requireable<ResizeHandlePlacement>;
    handleRender: PropTypes.Requireable<(...args: any[]) => any>;
    minimumSize: PropTypes.Requireable<number>;
    maximumSize: PropTypes.Requireable<number>;
    onResizeStart: PropTypes.Requireable<(...args: any[]) => any>;
    onResizeEnd: PropTypes.Requireable<(...args: any[]) => any>;
    id: PropTypes.Requireable<string>;
    className: PropTypes.Requireable<string>;
    style: PropTypes.Requireable<object>;
    as: PropTypes.Requireable<any>;
    centerContent: PropTypes.Requireable<import("..").CenterType>;
    zIndex: PropTypes.Requireable<number>;
    scrollable: PropTypes.Requireable<boolean>;
    trackSize: PropTypes.Requireable<boolean>;
    allowOverflow: PropTypes.Requireable<boolean>;
    onClick: PropTypes.Requireable<(...args: any[]) => any>;
    onDoubleClick: PropTypes.Requireable<(...args: any[]) => any>;
    onMouseDown: PropTypes.Requireable<(...args: any[]) => any>;
    onMouseEnter: PropTypes.Requireable<(...args: any[]) => any>;
    onMouseLeave: PropTypes.Requireable<(...args: any[]) => any>;
    onMouseMove: PropTypes.Requireable<(...args: any[]) => any>;
    onTouchStart: PropTypes.Requireable<(...args: any[]) => any>;
    onTouchMove: PropTypes.Requireable<(...args: any[]) => any>;
    onTouchEnd: PropTypes.Requireable<(...args: any[]) => any>;
};
export interface IArchbaseAnchorProps extends IArchbaseResizableProps {
    resizable?: boolean;
}
export declare const anchoredProps: {
    resizable: PropTypes.Requireable<boolean>;
    size: PropTypes.Validator<NonNullable<NonNullable<string | number>>>;
    order: PropTypes.Requireable<number>;
    handleSize: PropTypes.Requireable<number>;
    touchHandleSize: PropTypes.Requireable<number>;
    handlePlacement: PropTypes.Requireable<ResizeHandlePlacement>;
    handleRender: PropTypes.Requireable<(...args: any[]) => any>;
    minimumSize: PropTypes.Requireable<number>;
    maximumSize: PropTypes.Requireable<number>;
    onResizeStart: PropTypes.Requireable<(...args: any[]) => any>;
    onResizeEnd: PropTypes.Requireable<(...args: any[]) => any>;
    id: PropTypes.Requireable<string>;
    className: PropTypes.Requireable<string>;
    style: PropTypes.Requireable<object>;
    as: PropTypes.Requireable<any>;
    centerContent: PropTypes.Requireable<import("..").CenterType>;
    zIndex: PropTypes.Requireable<number>;
    scrollable: PropTypes.Requireable<boolean>;
    trackSize: PropTypes.Requireable<boolean>;
    allowOverflow: PropTypes.Requireable<boolean>;
    onClick: PropTypes.Requireable<(...args: any[]) => any>;
    onDoubleClick: PropTypes.Requireable<(...args: any[]) => any>;
    onMouseDown: PropTypes.Requireable<(...args: any[]) => any>;
    onMouseEnter: PropTypes.Requireable<(...args: any[]) => any>;
    onMouseLeave: PropTypes.Requireable<(...args: any[]) => any>;
    onMouseMove: PropTypes.Requireable<(...args: any[]) => any>;
    onTouchStart: PropTypes.Requireable<(...args: any[]) => any>;
    onTouchMove: PropTypes.Requireable<(...args: any[]) => any>;
    onTouchEnd: PropTypes.Requireable<(...args: any[]) => any>;
};
export declare const ArchbaseSpaceLeftResizable: React.FC<IArchbaseResizableProps>;
export declare const ArchbaseSpaceLeft: React.FC<IArchbaseAnchorProps>;
export declare const ArchbaseSpaceTopResizable: React.FC<IArchbaseResizableProps>;
export declare const ArchbaseSpaceTop: React.FC<IArchbaseAnchorProps>;
export declare const ArchbaseSpaceRightResizable: React.FC<IArchbaseResizableProps>;
export declare const ArchbaseSpaceRight: React.FC<IArchbaseAnchorProps>;
export declare const ArchbaseSpaceBottomResizable: React.FC<IArchbaseResizableProps>;
export declare const ArchbaseSpaceBottom: React.FC<IArchbaseAnchorProps>;
//# sourceMappingURL=ArchbaseSpaceAnchored.d.ts.map