export const languages = {
  pt_br: {
    name: 'Nome',
    save: 'Salvar',
    saveAs: 'Salvar...',
    back: 'Voltar',
    loading: 'Carregando...',
    resetOperations: 'Redefinir/excluir todas as operações',
    changesLoseConfirmation: 'Todas as alterações serão perdidas',
    changesLoseConfirmationHint: 'Você tem certeza que quer continuar?',
    cancel: 'Cancela',
    continue: 'Continue',
    undoTitle: 'Desfazer última operação',
    redoTitle: 'Refazer última operação',
    showImageTitle: 'Show original image',
    zoomInTitle: 'Mais Zoom',
    zoomOutTitle: 'Reduzir o zoom',
    toggleZoomMenuTitle: 'Alternar menu de zoom',
    adjustTab: 'Ajustar',
    finetuneTab: 'Afinar',
    filtersTab: 'Filtros',
    watermarkTab: "Marca d'água",
    annotateTab: 'Desenhar',
    resize: 'Tamanho',
    resizeTab: 'Tamanho',
    invalidImageError: 'Imagem inválida fornecida.',
    uploadImageError: 'Erro ao carregar a imagem.',
    areNotImages: 'não são imagens',
    isNotImage: 'não é imagem',
    toBeUploaded: 'para ser carregado',
    cropTool: 'Cortar',
    original: 'Original',
    custom: 'Personalizado',
    square: 'Quadrado',
    landscape: 'Paisagem',
    portrait: 'Retrato',
    ellipse: 'Elipse',
    classicTv: 'TV Clássica',
    cinemascope: 'Cinemascópio',
    arrowTool: 'Seta',
    blurTool: 'Borrão',
    brightnessTool: 'Brilho',
    contrastTool: 'Contraste',
    ellipseTool: 'Elipse',
    unFlipX: 'Desvirar X',
    flipX: 'Virar X',
    unFlipY: 'Desvirar Y',
    flipY: 'Virar Y',
    hsvTool: 'HSV',
    hue: 'Hue',
    saturation: 'Saturação',
    value: 'valor',
    imageTool: 'Imagem',
    importing: 'Importando...',
    addImage: '+ Adicionar image',
    uploadImage: 'Upload imagem',
    fromGallery: 'Da galeria',
    lineTool: 'Linha',
    penTool: 'Caneta',
    polygonTool: 'Poligono',
    sides: 'Lados',
    rectangleTool: 'Retângulo',
    cornerRadius: 'Corner Radius',
    resizeWidthTitle: 'Largura em pixels',
    resizeHeightTitle: 'Altura em pixels',
    toggleRatioLockTitle: 'Bloqueio de proporção de alternância',
    reset: 'Reiniciar',
    resetSize: 'Redefinir p/o tamanho original imagem',
    rotateTool: 'Girar',
    textTool: 'Texto',
    textSpacings: 'Espaçamentos texto',
    textAlignment: 'Alinhamento texto',
    fontFamily: 'Família fontes',
    size: 'Tamanho',
    letterSpacing: 'Espaçamento entre Letras',
    lineHeight: 'Altura da linha',
    warmthTool: 'Cordialidade',
    addWatermark: "+ Adicione Marca D'água",
    addTextWatermark: "+ Adicionar marca d'água texto",
    addWatermarkTitle: "Escolha o tipo de marca d'água",
    uploadWatermark: "Upload marca d'água",
    addWatermarkAsText: 'Adicionar como texto',
    padding: 'Preenchimento',
    shadow: 'Sombra',
    horizontal: 'Horizontal',
    vertical: 'Vertical',
    blur: 'Borrão',
    opacity: 'Opacidade',
    position: 'Posição',
    stroke: 'AVC',
    saveAsModalLabel: 'Salve a imagem como',
    extension: 'Extensão',
    nameIsRequired: 'O nome é obrigatório.',
    quality: 'Qualidade',
    imageDimensionsHoverTitle: 'Tamanho da imagem salva (largura x altura)',
    cropSizeLowerThanResizedWarning:
      'Observe que a área de corte selecionada é menor do que o redimensionamento aplicado, o que pode causar diminuição da qualidade',
    actualSize: 'Tamanho atual (100%)',
    fitSize: 'Tamanho adequado',
    addImageTitle: 'Selecione a imagem para adicionar...',
  },
  en: {
    name: 'Name',
    save: 'Save',
    saveAs: 'Save as',
    back: 'Back',
    loading: 'Loading...',
    resetOperations: 'Reset/delete all operations',
    changesLoseConfirmation: 'All changes will be lost',
    changesLoseConfirmationHint: 'Are you sure you want to continue?',
    cancel: 'Cancel',
    continue: 'Continue',
    undoTitle: 'Undo last operation',
    redoTitle: 'Redo last operation',
    showImageTitle: 'Show original image',
    zoomInTitle: 'Zoom in',
    zoomOutTitle: 'Zoom out',
    toggleZoomMenuTitle: 'Toggle zoom menu',
    adjustTab: 'Adjust',
    finetuneTab: 'Finetune',
    filtersTab: 'Filters',
    watermarkTab: 'Watermark',
    annotateTab: 'Draw',
    resize: 'Resize',
    resizeTab: 'Resize',
    invalidImageError: 'Invalid image provided.',
    uploadImageError: 'Error while uploading the image.',
    areNotImages: 'are not images',
    isNotImage: 'is not image',
    toBeUploaded: 'to be uploaded',
    cropTool: 'Crop',
    original: 'Original',
    custom: 'Custom',
    square: 'Square',
    landscape: 'Landscape',
    portrait: 'Portrait',
    ellipse: 'Ellipse',
    classicTv: 'Classic TV',
    cinemascope: 'Cinemascope',
    arrowTool: 'Arrow',
    blurTool: 'Blur',
    brightnessTool: 'Brightness',
    contrastTool: 'Contrast',
    ellipseTool: 'Ellipse',
    unFlipX: 'Un-Flip X',
    flipX: 'Flip X',
    unFlipY: 'Un-Flip Y',
    flipY: 'Flip Y',
    hsvTool: 'HSV',
    hue: 'Hue',
    saturation: 'Saturation',
    value: 'Value',
    imageTool: 'Image',
    importing: 'Importing...',
    addImage: '+ Add image',
    uploadImage: 'Upload image',
    fromGallery: 'From gallery',
    lineTool: 'Line',
    penTool: 'Pen',
    polygonTool: 'Polygon',
    sides: 'Sides',
    rectangleTool: 'Rectangle',
    cornerRadius: 'Corner Radius',
    resizeWidthTitle: 'Width in pixels',
    resizeHeightTitle: 'Height in pixels',
    toggleRatioLockTitle: 'Toggle ratio lock',
    reset: 'Reset',
    resetSize: 'Reset to original image size',
    rotateTool: 'Rotate',
    textTool: 'Text',
    textSpacings: 'Text spacings',
    textAlignment: 'Text alignment',
    fontFamily: 'Font family',
    size: 'Size',
    letterSpacing: 'Letter Spacing',
    lineHeight: 'Line height',
    warmthTool: 'Warmth',
    addWatermark: '+ Add watermark',
    addTextWatermark: '+ Add text watermark',
    addWatermarkTitle: 'Choose the watermark type',
    uploadWatermark: 'Upload watermark',
    addWatermarkAsText: 'Add as text',
    padding: 'Padding',
    shadow: 'Shadow',
    horizontal: 'Horizontal',
    vertical: 'Vertical',
    blur: 'Blur',
    opacity: 'Opacity',
    position: 'Position',
    stroke: 'Stroke',
    saveAsModalLabel: 'Save the image as',
    extension: 'Extension',
    nameIsRequired: 'Name is required.',
    quality: 'Quality',
    imageDimensionsHoverTitle: 'Saved image size (width x height)',
    cropSizeLowerThanResizedWarning: 'Note, the selected crop area is lower than the applied resize which might cause quality decrease',
    actualSize: 'Actual size (100%)',
    fitSize: 'Fit size',
    addImageTitle: 'Select image to add...',
  },
  es: {
    name: 'Nombre',
    save: 'Guardar',
    saveAs: 'Guardar...',
    back: 'Atrás',
    loading: 'Cargando...',
    resetOperations: 'Restablecer/eliminar todas las operaciones',
    changesLoseConfirmation: 'Todos los cambios se perderán',
    changesLoseConfirmationHint: '¿Estás seguro de que quieres continuar?',
    cancel: 'Cancelar',
    continue: 'Continuar',
    undoTitle: 'Deshacer última operación',
    redoTitle: 'Rehacer última operación',
    showImageTitle: 'Mostrar imagen original',
    zoomInTitle: 'Acercarse',
    zoomOutTitle: 'Disminuir el zoom',
    toggleZoomMenuTitle: 'Alternar menú de zoom',
    adjustTab: 'Ajustar',
    finetuneTab: 'Afinar',
    filtersTab: 'Filtros',
    watermarkTab: 'Filigrana',
    annotateTab: 'diseñar',
    resize: 'Tamaño',
    resizeTab: 'Tamaño',
    invalidImageError: 'Imagen proporcionada no válida.',
    uploadImageError: 'Error al cargar la imagen.',
    areNotImages: 'no son imágenes',
    isNotImage: 'no es imagen',
    toBeUploaded: 'para ser subido',
    cropTool: 'Recortar',
    original: 'Original',
    personalizado: 'Personalizado',
    cuadrado: 'Cuadrado',
    paisaje: 'Paisaje',
    retrato: 'Retrato',
    elipse: 'Elipse',
    classicTv: 'Televisión clásica',
    cinemascope: 'Cinemascope',
    arrowTool: 'Flecha',
    blurTool: 'Difuminar',
    brightnessTool: 'Brillo',
    contrastTool: 'Contraste',
    ellipseTool: 'Elipse',
    unFlipX: 'Des-Voltear X',
    flipX: 'Voltear X',
    unFlipY: 'Un-Flip Y',
    flipY: 'Voltear Y',
    hsvTool: 'HSV',
    hue: 'Hue',
    saturation: 'Saturación',
    value: 'Valor',
    imageTool: 'Imagen',
    importing: 'Importador...',
    addImage: '+ Añadir imagen',
    uploadImage: 'Cargar imagen',
    fromGallery: 'De la galería',
    lineTool: 'Línea',
    penTool: 'Bolígrafo',
    polygonTool: 'Polígono',
    sides: 'Lados',
    rectangleTool: 'Rectángulo',
    cornerRadius: 'Radio de esquina',
    resizeWidthTitle: 'Ancho en píxeles',
    resizeHeightTitle: 'Altura en píxeles',
    toggleRatioLockTitle: 'Conmutar bloqueo de relación',
    reset: 'Reiniciar',
    resetSize: 'Restablecer al tamaño de imagen original',
    rotateTool: 'Girar',
    textTool: 'Texto',
    textSpacings: 'Espaciamientos de texto',
    textAlignment: 'Alineación del texto',
    fontFamily: 'Familia tipográfica',
    size: 'Tamaño',
    letterSpacing: 'Espaciado de letras',
    lineHeight: 'Altura de la línea',
    warmthTool: 'Calor',
    addWatermark: '+ Agregar marca de agua',
    addTextWatermark: '+ Agregar marca de agua de texto',
    addWatermarkTitle: 'Elija el tipo de marca de agua',
    uploadWatermark: 'Upload filigrana',
    addWatermarkAsText: 'Agregar como texto',
    padding: 'Relleno',
    shadow: 'Sombra',
    horizontal: 'Horizontal',
    vertical: 'Vertical',
    blur: 'Difuminar',
    opacity: 'Opacidad',
    position: 'Posición',
    stroke: 'Ataque',
    saveAsModalLabel: 'Guardar la imagen como',
    extension: 'Extensión',
    nameIsRequired: 'Se requiere el nombre.',
    quality: 'Calidad',
    imageDimensionsHoverTitle: 'Tamaño de la imagen guardada (ancho x alto)',
    cropSizeLowerThanResizedWarning:
      'Tenga en cuenta que el área de recorte seleccionada es menor que el cambio de tamaño aplicado, lo que podría causar una disminución de la calidad',
    actualSize: 'Tamaño real (100%)',
    fitSize: 'Tamaño de ajuste',
    addImageTitle: 'Seleccionar imagen para agregar...',
  },
};
