declare const EQ: "==";
declare const NEQ: "!=";
declare const LE: "<=";
declare const GE: ">=";
declare const LT: "<";
declare const GT: ">";
declare const IN: "=in=";
declare const OUT: "=out=";
declare const BT: "=bt=";
declare const NB: "=nb=";
declare const LE_VERBOSE: "=le=";
declare const GE_VERBOSE: "=ge=";
declare const LT_VERBOSE: "=lt=";
declare const GT_VERBOSE: "=gt=";
type CustomComparisonOperator = string;
declare const CanonicalComparisonOperators: ("!=" | ">" | "<" | ">=" | "<=" | "==" | "=in=" | "=out=" | "=bt=" | "=nb=")[];
type CanonicalComparisonOperator = (typeof CanonicalComparisonOperators)[number];
declare const VerboseComparisonOperators: ("=le=" | "=ge=" | "=lt=" | "=gt=")[];
type VerboseComparisonOperator = (typeof VerboseComparisonOperators)[number];
declare const ComparisonOperators: ("!=" | ">" | "<" | ">=" | "<=" | "==" | "=in=" | "=out=" | "=bt=" | "=nb=" | "=le=" | "=ge=" | "=lt=" | "=gt=")[];
type ComparisonOperator = (typeof ComparisonOperators)[number] | CustomComparisonOperator;
declare function isComparisonOperator(candidate: string, operator?: ComparisonOperator): candidate is ComparisonOperator;
export { EQ, NEQ, LE, GE, LT, GT, IN, OUT, BT, NB, LE_VERBOSE, GE_VERBOSE, LT_VERBOSE, GT_VERBOSE, ComparisonOperators, CanonicalComparisonOperators, VerboseComparisonOperators, isComparisonOperator, };
export type { ComparisonOperator, CanonicalComparisonOperator, VerboseComparisonOperator };
//# sourceMappingURL=ComparisonOperator.d.ts.map