name: Semantic Release
on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: |
          yarn install

      - name: Build components
        run: |
          yarn run build

      - name: Run semantic-release
        env:
          GH_TOKEN: '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'
          NPM_TOKEN: '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'
        run: npx semantic-release
